consumer_key: 'CONSUMERKEY'
access_token: 'ACCESSTOKEN'

sites:
  sitename:
    url: "https://www.example.com/blog/rss"
    tags:
      - tag
      - anothertag
  anothersite:
    url: "https://www.example.com/feed"
    tags:
      - it